### ISSUE TITLE
SCAPI file optain

### ISSUE THREAD

**Issue by Akshaycons** [cnayan/SiebelCTIConector#1]
Hi Nayan,

Can you please  guide us how to optain SCAPI file.We want to cretae our own driver.

**Comment by cnayan** [comment]
You need to ask Siebel Support for the file.

**Comment by Akshaycons** [comment]
Hi Nayan,

Thanks for the information.We have raised SR with oracle for the file.Need to your help for integration.
Any contact number where we can connect.
My email id is akshay.gupta@consiliuminc.com

**Comment by PauloTroguilho** [comment]
Error ! helpe me please, error in compiler
SiebelCTIConnector-master\S_CTI\h\Param.h	[Error] 'ISC_STRING' does not name a type
AgentService.h	[Error] 'ISC_CLIENT_INTERFACE' does not name a type
AgentService.h	[Error] 'eUNKNOWN' was not declared in this scope

**Comment by cnayan** [comment]
@PauloTroguilho Please open another thread and give details on what you were trying to build, environment details, build tools, along with the complete error log. Thanks
