### ISSUE TITLE
erro compiler dll

### ISSUE THREAD

**Issue by PauloTroguilho** [cnayan/SiebelCTIConector#2]
dear cnayan,
I am trying to create the dll of your project to use as a base in communicating with siebel, but I can not reproduce it shows me some errors, I am using a windows server 2012 system, Dev-Cpp 5.11 TDM-GCC 4.9.2 mode release 32 bits , follows some logs errors are in agentservice.cpp and agentservice.h

> 31 C: \ Users \ corsidian \ Desktop \ SiebelCTIConnector-master \ SiebelCTIConnector-master \ S_CTI \ Makefile.win recipe for target 'cpp / AgentService.o' failed

> C: \ Users \ corsidian \ Desktop \ SiebelCTIConnector-master \ SiebelCTIConnector-master \ S_CTI \ h \ Param.h [Error] 'ISC_STRING' does not name a type

> 38 1 C: \ Users \ corsidian \ Desktop \ SiebelCTIConnector-master \ SiebelCTIConnector-master \ S_CTI \ h \ CTI.h [Error] 'ISC_RESULT' does not name a type

Abaixo algumas das linhas que deu erro

`cpp/AgentService.o: cpp/AgentService.cpp
	$(CPP) -c cpp/AgentService.cpp -o cpp/AgentService.o $(CXXFLAGS)`

`public:
	Param(JobType jt, const struct ISC_KVParamList*, const ISC_STRING& requestName);`

Thank you for the feedback and attention.

do u have whatsapp

**Comment by PauloTroguilho** [comment]
I would like to create the dll

**Comment by cnayan** [comment]
Hi @PauloTroguilho ,

I think you do not have the Siebel header file, **scapi.h**, that is required.

I don't own it and cannot provide it. You have to request Siebel team.
Consult this thread for additional info: [https://it.toolbox.com/question/siebel-78-scapih-comm-driver-implementation-092805](https://it.toolbox.com/question/siebel-78-scapih-comm-driver-implementation-092805)

Without that important header file, you cannot build this code.

**Comment by PauloTroguilho** [comment]
ok, I'll ask them for the return, and let me ask you how long it took to develop this on top of the documentation of them I was trying and already have months ago

**Comment by PauloTroguilho** [comment]
Hi @cnayan ,


I got the file and tried again to compile, I generate some errors could guide me please.

There are errors.

In file included from cpp/AgentService.cpp:

`AgentState agentState = eUNKNOWN;`

> [Error] 'eUNKNOWN' was not declared in this scope

In member function 'void AgentService::UpdateSiebelUI()':

`if (agentState == eNON_ACD)`
`else if (agentState != eLOG_OUT && agentState != eNON_ACD)`

> [Error] 'eLOG_OUT' was not declared in this scope

**Comment by PauloTroguilho** [comment]
Log Full
> 1	0	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	In file included from cpp/AgentService.cpp

> 18	26	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\h\AgentService.h	[Error] 'eUNKNOWN' was not declared in this scope

> C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	In member function 'void AgentService::UpdateSiebelUI()':

> 104	21	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	[Error] 'eNON_ACD' was not declared in this scope

> 108	26	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	[Error] 'eLOG_OUT' was not declared in this scope

> 121	21	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	[Error] 'eNON_ACD' was not declared in this scope

> 125	26	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	[Error] 'eLOG_OUT' was not declared in this scope

> 31		C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\Makefile.win	recipe for target 'cpp/AgentService.o' failed
