### ISSUE TITLE
Error not declared in the scope

### ISSUE THREAD

**Issue by PauloTroguilho** [cnayan/SiebelCTIConector#3]
Hi @cnayan ,

I got the file and tried again to compile, I generate some errors could guide me please.

There are errors.

In file included from cpp/AgentService.cpp:

`AgentState agentState = eUNKNOWN;`

> [Error] 'eUNKNOWN' was not declared in this scope

In member function 'void AgentService::UpdateSiebelUI()':

`if (agentState == eNON_ACD)`
`else if (agentState != eLOG_OUT && agentState != eNON_ACD)`

> [Error] 'eLOG_OUT' was not declared in this scope

Log Full
> 1	0	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	In file included from cpp/AgentService.cpp

> 18	26	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\h\AgentService.h	[Error] 'eUNKNOWN' was not declared in this scope

> C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	In member function 'void AgentService::UpdateSiebelUI()':

> 104	21	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	[Error] 'eNON_ACD' was not declared in this scope

> 108	26	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	[Error] 'eLOG_OUT' was not declared in this scope

> 121	21	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	[Error] 'eNON_ACD' was not declared in this scope

> 125	26	C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\cpp\AgentService.cpp	[Error] 'eLOG_OUT' was not declared in this scope

> 31		C:\Users\PAULO TROGUILHO\Downloads\SiebelCTIConnector-master\S_CTI\Makefile.win	recipe for target 'cpp/AgentService.o' failed

**Comment by PauloTroguilho** [comment]
I think these enums are missing

> eUNKNOWN
> eNON_ACD
> eLOG_OUT

**Comment by cnayan** [comment]
The enums are in CTI.h file.
Please add the missing states as you see fit. I'll fill in the gap very soon.

```
enum AgentState
{
	UNKNOWN = -1,
	AUTO_IN,
	MANUAL_IN,
	AUX_WORK,
	AFTER_CALL_WORK,
	LOG_OUT
};
```
